#ifndef STEREO_FILTER_CONFIG_H
#define STEREO_FILTER_CONFIG_H

#ifndef ROBOT_STEREO_ONE_EURO_ENABLE
#define ROBOT_STEREO_ONE_EURO_ENABLE 1
#endif

#if ROBOT_STEREO_ONE_EURO_ENABLE != 0 && ROBOT_STEREO_ONE_EURO_ENABLE != 1
#error ROBOT_STEREO_ONE_EURO_ENABLE must be 0 or 1
#endif

#endif
