#ifndef STEREO_FILTER_CONFIG_H
#define STEREO_FILTER_CONFIG_H

#ifndef ROBOT_STEREO_ONE_EURO_ENABLE
#define ROBOT_STEREO_ONE_EURO_ENABLE 1
#endif

#ifndef ROBOT_STEREO_ONE_EURO_TUNABLE
#define ROBOT_STEREO_ONE_EURO_TUNABLE 0
#endif

#ifndef ROBOT_STEREO_FILTER_NAME
#define ROBOT_STEREO_FILTER_NAME "G_KALMAN"
#endif

#if ROBOT_STEREO_ONE_EURO_ENABLE != 0 && ROBOT_STEREO_ONE_EURO_ENABLE != 1
#error ROBOT_STEREO_ONE_EURO_ENABLE must be 0 or 1
#endif

#endif
