class cnn_c06_reset_seq extends cnn_ctrl_base_seq;
    `uvm_object_utils(cnn_c06_reset_seq)

    virtual cnn_if vif;
    localparam string FSM_PATH = "tb_top.dut.u_top_level_fsm.";
    bit [1:0] reset_type_hits;  // bit 0=soft, bit 1=hard
    bit [2:0] reset_point_hits; // bit 0=idle, bit 1=busy, bit 2=error
    int sampled_type, sampled_point;

    covergroup reset_cg;
        option.per_instance = 1;
        // Commands generated by this scenario, not inferred from log text.
        cp_type: coverpoint sampled_type {
            bins soft = {0}; bins hard = {1};
        }
        // Representative reset locations that the stimulus actually reaches.
        cp_point: coverpoint sampled_point {
            bins idle = {0}; bins busy = {1}; bins error = {2};
        }
    endgroup

    function new(string name = "cnn_c06_reset_seq");
        super.new(name);
        reset_cg = new();
    endfunction

    function void record_reset(int reset_type, int reset_point);
        sampled_type = reset_type;
        sampled_point = reset_point;
        reset_type_hits[reset_type] = 1;
        reset_point_hits[reset_point] = 1;
        reset_cg.sample();
    endfunction

    task check_idle_and_defaults(string label);
        cnn_c01_reset_seq defaults;
        uvm_hdl_data_t value;
        // Reuse the existing frontdoor C01 read checks after each reset.
        defaults = cnn_c01_reset_seq::type_id::create({label, "_defaults"});
        defaults.start(m_sequencer);
        if (!uvm_hdl_read({FSM_PATH, "state"}, value) || value[4:0] != 0)
            `uvm_error("C06_IDLE", $sformatf("%s FSM did not return to IDLE", label))
        read_check(REG_CYCLE_COUNT, 32'd0, {label, " cycle_count"});
    endtask

    task wait_busy();
        bit [31:0] status;
        bit [1:0] resp;
        for (int tries = 0; tries < 50; tries++) begin
            read_reg(REG_STATUS, status, resp);
            if (resp == 0 && status[1]) return;
        end
        `uvm_fatal("C06_BUSY", "START did not enter BUSY")
    endtask

    task wait_error();
        bit [31:0] status;
        bit [1:0] resp;
        for (int tries = 0; tries < 50; tries++) begin
            read_reg(REG_STATUS, status, resp);
            if (resp == 0 && status[2] && !status[1]) return;
        end
        `uvm_fatal("C06_ERROR", "Injected module fault did not create error_pending")
    endtask

    task start_and_wait();
        write_resp_check(REG_CONTROL, 32'h1, 4'hf, 2'b00, "C06_START");
        wait_busy();
    endtask

    task body();
        uvm_hdl_data_t value;
        if (vif == null) `uvm_fatal("C06_VIF", "Test did not pass cnn_if")

        // IDLE soft reset: command through the public AXI-Lite frontdoor.
        record_reset(0, 0);
        write_resp_check(REG_CONTROL, 32'h4, 4'hf, 2'b00, "IDLE_SOFT_RESET");
        check_idle_and_defaults("idle_soft");

        // BUSY soft reset: the common zero-status responder holds stage 0,
        // providing a deterministic early-stage in-flight reset location.
        start_and_wait();
        record_reset(0, 1);
        write_resp_check(REG_CONTROL, 32'h4, 4'hf, 2'b00, "BUSY_SOFT_RESET");
        check_idle_and_defaults("busy_soft");

        // Hard reset drives only tb_top.rst_n, the same input used by tb_top.
        // It does not force any expected DUT state or result value.
        start_and_wait();
        record_reset(1, 1);
        if (!uvm_hdl_force("tb_top.rst_n", 1'b0))
            `uvm_fatal("C06_HARD_FORCE", "Cannot force tb_top.rst_n")
        repeat (5) @(posedge vif.clk);
        // tb_top.rst_n is a procedural variable, so releasing a LOW force
        // alone leaves its last value LOW. Drive its deasserted value first.
        if (!uvm_hdl_force("tb_top.rst_n", 1'b1))
            `uvm_fatal("C06_HARD_DEASSERT", "Cannot deassert tb_top.rst_n")
        repeat (2) @(posedge vif.clk);
        if (!uvm_hdl_release("tb_top.rst_n"))
            `uvm_fatal("C06_HARD_RELEASE", "Cannot release tb_top.rst_n")
        repeat (3) @(posedge vif.clk);
        if (!uvm_hdl_read("tb_top.rst_n", value) || !value[0])
            `uvm_fatal("C06_HARD_RELEASE", "tb_top.rst_n remained LOW after release")
        check_idle_and_defaults("busy_hard");

        // Create an actual module-fault input while BUSY, then ask the RTL
        // soft-reset path to recover from its own ERROR state.
        start_and_wait();
        if (!uvm_hdl_force({FSM_PATH, "input_fault"}, 1'b1))
            `uvm_fatal("C06_FAULT_FORCE", "Cannot inject module fault input")
        wait_error();
        if (!uvm_hdl_release({FSM_PATH, "input_fault"}))
            `uvm_fatal("C06_FAULT_RELEASE", "Cannot release module fault input")
        read_check(REG_ERROR_CODE, 32'h1, "module fault error code");
        record_reset(0, 2);
        write_resp_check(REG_CONTROL, 32'h4, 4'hf, 2'b00, "ERROR_SOFT_RESET");
        check_idle_and_defaults("error_soft");

        // Recovery includes accepting another normal START.
        start_and_wait();
        write_resp_check(REG_CONTROL, 32'h4, 4'hf, 2'b00, "RECOVERY_CLEANUP");
        check_idle_and_defaults("recovery");
        `uvm_info("C06_COVERAGE", $sformatf("reset_types=%02b positions=%03b coverage=%0.1f%%",
                                           reset_type_hits, reset_point_hits,
                                           reset_cg.get_coverage()), UVM_LOW)
    endtask
endclass
