#ifndef G_VARIANT_CONFIG_H
#define G_VARIANT_CONFIG_H

#ifndef G_KALMAN_SIGMA_XY_MM
#define G_KALMAN_SIGMA_XY_MM 8.0f
#endif
#ifndef G_KALMAN_SIGMA_Z_MM
#define G_KALMAN_SIGMA_Z_MM 70.0f
#endif
#ifndef G_KALMAN_ACCEL_STD_MM_S2
#define G_KALMAN_ACCEL_STD_MM_S2 500.0f
#endif
#ifndef G_KALMAN_INITIAL_VELOCITY_STD_MM_S
#define G_KALMAN_INITIAL_VELOCITY_STD_MM_S 500.0f
#endif

#define G_KALMAN_RESET_GAP_US UINT64_C(500000)
#define G_VARIANT_BACKEND_LABEL "G_KALMAN"

#endif
