#ifndef TEST_CAPTURE_XAXIVDMA_HW_H
#define TEST_CAPTURE_XAXIVDMA_HW_H
#include "xil_types.h"
#define XAXIVDMA_SR_OFFSET 4U
#define XAXIVDMA_CR_OFFSET 0U
#define XAXIVDMA_CR_RUNSTOP_MASK 1U
#define XAXIVDMA_CR_TAIL_EN_MASK 2U
#define XAXIVDMA_CR_FRMCNT_EN_MASK 0x10U
#define XAXIVDMA_FRMCNT_MASK 0x00FF0000U
#define XAXIVDMA_FRMCNT_SHIFT 16U
#define XAXIVDMA_SR_HALTED_MASK 1U
#define XAXIVDMA_IXR_FRMCNT_MASK 0x1000U
#define XAXIVDMA_PARKPTR_OFFSET 0x28U
#define XAXIVDMA_PARKPTR_WRTREF_MASK 0x1F00U
u32 XAxiVdma_ReadReg(UINTPTR base, u32 offset);
void XAxiVdma_WriteReg(UINTPTR base, u32 offset, u32 value);
#endif
